# Nombre del flujo de trabajo que aparecerá en la pestaña "Actions" de GitHub
name: 'Pipeline de Datos CI'

# Define cuándo se ejecutará este flujo de trabajo
on:
  push:
    branches: [ main ] # Se ejecuta en cada push a la rama principal
  pull_request:
    branches: [ main ] # Se ejecuta en cada pull request a la rama principal

# Define los trabajos (jobs) que se ejecutarán
jobs:
  validate_dag:
    # Nombre del trabajo
    name: 'Validar Sintaxis del DAG'
    # El tipo de máquina virtual en la que se ejecutará
    runs-on: ubuntu-latest

    # Los pasos que se ejecutarán secuencialmente
    steps:
      # Paso 1: Descargar una copia de tu código del repositorio
      - name: 'Checkout del código'
        uses: actions/checkout@v4

      # Paso 2: Configurar el entorno de Python
      - name: 'Configurar Python 3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Paso 3: Instalar las dependencias de Airflow necesarias para la validación
      - name: 'Instalar dependencias'
        run: pip install -r requirements-dev.txt

      # Paso 4: Ejecutar la prueba de sintaxis en el archivo del DAG
      # python -m compileall compila el archivo a bytecode. Si hay un error de sintaxis, fallará.
      - name: 'Verificar sintaxis del DAG de Airflow'
        run: python -m compileall airflow/dags/elt_pipeline_dag.py

